apiVersion: v1
kind: Service
metadata:
  name: tomcat-sample-war-service
spec:
  ports:
    - name: http 
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32227
    - name: jmx 
      port: 8099
      protocol: TCP
      targetPort: 8099
      nodePort: 32228
  selector:
    app: tomcat-sample-war
  type: NodePort
